### ISSUE TITLE
Nav component deprecated

### ISSUE THREAD

**Issue by karanrajpal14** [hivickylai/hugo-theme-introduction#42] opened 2018-04-19 05:13 UTC
The `nav` component has been deprecated and the latest versions of bulma have moved to `navbar`. As a result, `nav-center` doesn't work anymore. 
Look [here][1] and [here][2]

[1]: https://github.com/jgthms/bulma/issues/894
[2]: https://bulma.io/documentation/components/nav/

**Comment by hivickylai** [comment] 2018-05-03 14:47
Duplicate of #29 

Rewriting CSS without the use of Bulma is desired, see referenced issue.

**Closed by hivickylai** 2018-05-03 14:47 UTC
Labels: good first issue, help wanted
